### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by klgor1803** [denyshorman/visualkey#3]
It would be really cool to have a button to automatically generate random keys

**Comment by denyshorman** [comment]
This functionality is supported.  
The third button from the left generates a random key.  
![image](https://github.com/user-attachments/assets/f439bde3-6542-461f-a35c-a69d9c6806b9)
Press and hold the button for one second to activate automatic generation mode.  
Is this what you're looking for?

**Comment by Klgor1803** [comment]
yes! I didn't know that

**Comment by denyshorman** [comment]
Awesome. Have fun with it! :grin:

**Comment by KleinAiGen** [comment]
Hi! Could you make it so that only lower case letters are used for the generated address? The way I looked at it most of the addresses don't have A-Z, just a-z. Thanks

**Comment by KleinAiGen** [comment]
B.W  awsome app, thanks for sharing this fun with us!

**Comment by denyshorman** [comment]
Hi @KleinAiGen and thanks for the feedback! Right now, the app displays Ethereum addresses in the checksum format (EIP-55), which includes both uppercase and lowercase letters. Technically, the app can render addresses in both lowercase and checksum formats, and each has its own pros and cons. Lowercase offers simplicity and consistency, while checksum formatting follows the Ethereum standard and helps detect errors caused by typos. I'd love to understand your use case better - would lowercase formatting make things easier for you in a specific way?

**Comment by KleinAiGen** [comment]
I was just browsing through a "couple" of  ethereum addresses, and I noticed that none of them contain A-Z karatert, so I'd better randomly exclude the ones that do. Thanks.
